name = "local/__WARREN_PROJECT_NAME__"

version = "0.1.0"

import {
  "moonbit-community/rabbita@0.12.4",
}

readme = "README.md"

repository = ""

license = "Apache-2.0"

keywords = [ ]

description = "A Rabbita app generated by Warren."

preferred_target = "js"
